version: '2'

services:
  control:
    build:
      context: ./docker
      dockerfile: Dockerfile-control
    hostname: control
    ports:
      - "2200:22"
    # The below environment shouldn't be needed because Ansible already looks
    # for the config in ~/ansible/ansible.cfg, but maybe the process of volume
    # mount is disrupting it. We can prioritize it's location search with the
    # ENV ANSIBLE_CONFIG.
    environment:
      - ANSIBLE_CONFIG=/root/ansible/ansible.cfg
    volumes:
      - ./ansible:/root/ansible
  awslinux1:
    build:
      context: ./docker
      dockerfile: Dockerfile-node
    hostname: awslinux1
    ports:
      - "2204:22"
      - "8080:80"
