version: '2'

services:
  control:
    build:
      context: ./docker
      dockerfile: Dockerfile-control
    container_name: control
    volumes:
      - ./ansible:/home/ansible/ansible
    ports:
      - "2200:22"
  ec1:
    build:
      context: ./docker
      dockerfile: Dockerfile-node
    container_name: ec1
    ports:
      - "2201:22"
      - "8081:80"
  ec2:
    build:
      context: ./docker
      dockerfile: Dockerfile-node
    container_name: ec2
    ports:
      - "2202:22"
      - "8082:80"
  ec3:
    build:
      context: ./docker
      dockerfile: Dockerfile-node
    container_name: ec3
    ports:
      - "2203:22"
      - "8083:80"
