version: '2'

services:
  control-jenkins:
    build:
      context: ./docker
      dockerfile: Dockerfile-jenkins
    container_name: jenkins-ansible
    networks:
      - ansible-net
    volumes:
      - ${PWD}/ansible:/etc/ansible/
      - ${PWD}/jenkins-data:/var/jenkins_home
      - jenkins-ssh:/var/jenkins_home/.ssh
    ports:
      - "8080:8080"
      - "2200:22"
      - "50000:50000"
#  control:
#    build:
#      context: ./docker
#      dockerfile: Dockerfile-control
#    container_name: control
##    volumes:
##      - ./ansible:/home/ansible/ansible
#    ports:
#      - "2210:22"
#    networks:
#      - ansible-net
  ec1:
    build:
      context: ./docker
      dockerfile: Dockerfile-node
    container_name: ec1
    networks:
      - ansible-net
    ports:
      - "2201:22"
      - "8081:80"
  ec2:
    build:
      context: ./docker
      dockerfile: Dockerfile-node
    container_name: ec2
    networks:
      - ansible-net
    ports:
      - "2202:22"
      - "8082:80"
  ec3:
    build:
      context: ./docker
      dockerfile: Dockerfile-node
    container_name: ec3
    networks:
      - ansible-net
    ports:
      - "2203:22"
      - "8083:80"
networks:
  ansible-net:
volumes:
  jenkins-ssh: