---
local:
  hosts:
    control:
      ansible_connection: local
aws:
  hosts:
    ec1:
      ansible_become: true
      ansible_become_pass: remote-ansible
#      ansible_port: 2222
    ec2:
    ec3:
  vars:
    ansible_user: remote-ansible
test:
  children:
    local:
    aws:
...