---
local:
  hosts:
    control-jenkins:
      ansible_connection: local
aws:
  hosts:
    ec1:
    ec2:
    ec3:
  vars:
    ansible_become: true
    ansible_user: remote-ansible
#    ansible_become_pass: remote-ansible
test:
  children:
    local:
    aws:
...
